// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Show forum home page and all articles",
                "responses": {
                    "200": {
                        "description": "Return an array of structure article",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.article"
                            }
                        }
                    }
                }
            }
        },
        "/article/create": {
            "get": {
                "summary": "Show article creation page",
                "responses": {}
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Create an article",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The title of the article",
                        "name": "title",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The content of the article",
                        "name": "content",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Create an article successfully",
                        "schema": {
                            "type": "int"
                        }
                    },
                    "400": {
                        "description": "Failed to create an article",
                        "schema": {
                            "type": "int"
                        }
                    }
                }
            }
        },
        "/article/view/:article_id": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Open the article page",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "The index of the article",
                        "name": "article_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Return the struct article",
                        "schema": {
                            "$ref": "#/definitions/main.article"
                        }
                    },
                    "404": {
                        "description": "Not found or invalid article_id",
                        "schema": {
                            "type": "int"
                        }
                    }
                }
            }
        },
        "/u/login": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Show the login page",
                "responses": {}
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Perform function login",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Password",
                        "name": "password",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Log in successfully",
                        "schema": {
                            "type": "int"
                        }
                    },
                    "400": {
                        "description": "Failed to log in",
                        "schema": {
                            "type": "int"
                        }
                    }
                }
            }
        },
        "/u/logout": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Logout",
                "responses": {}
            }
        },
        "/u/register": {
            "get": {
                "summary": "Show the registration page",
                "responses": {}
            },
            "post": {
                "summary": "Register a new user",
                "responses": {}
            }
        }
    },
    "definitions": {
        "main.article": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "UFMingle",
	Description: "An on-campus dating application",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
